# LLASA TTS trainer 設定例ファイル
# このファイルは設定の使用例を示しています

# =============================================================================
# 基本設定
# =============================================================================

# データとモデルパス
data_dir: dataset/data.jsonl          # 学習データのパス
output_dir: ./trained/MyModel           # 学習結果の保存先
model_name: NandemoGHS/Anime-Llasa-3B   # ベースモデル名

# CUDA設定
cuda_visible_devices: "0"               # 使用するGPU（"0,1"で複数GPU）

# =============================================================================
# LoRA設定 - モデルの微調整パラメータ
# =============================================================================
lora:
  r: 16                    # LoRAのランク（8-64推奨、大きいほど表現力UP、メモリ使用量UP）
  lora_alpha: 32          # スケーリング係数（通常はrの2倍）
  lora_dropout: 0.05      # ドロップアウト率（0.0-0.1）
  bias: none              # バイアス学習（none/all/lora_only）
  target_modules:         # LoRAを適用するレイヤー
    - q_proj
    - k_proj  
    - v_proj
    - o_proj

# =============================================================================
# 学習設定
# =============================================================================
training:
  num_train_epochs: 20                  # エポック数
  per_device_train_batch_size: 1        # デバイス当たりのバッチサイズ
  gradient_accumulation_steps: 8        # 勾配蓄積ステップ（実効バッチサイズ = batch_size * accumulation）
  learning_rate: 1e-4                   # 学習率
  weight_decay: 0.01                    # 重み減衰
  save_steps: 100                       # 保存間隔（ステップ）
  save_total_limit: 3                   # 保存する最大チェックポイント数
  fp16: true                           # 16bit精度使用（メモリ節約）
  gradient_checkpointing: false         # 勾配チェックポイント（メモリ vs 速度）
  warmup_ratio: 0.03                   # ウォームアップ比率
  lr_scheduler_type: cosine            # 学習率スケジューラ
  report_to: null                      # ログ出力先（wandb/tensorboard/null）

# =============================================================================
# テスト設定 - 学習中の音声生成テスト
# =============================================================================
test:
  text: 天使ちゃんマジ天使。        # テスト用テキスト
  interval: 50                         # テスト実行間隔（ステップ）