name: Python Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Check Python syntax
      run: |
        python -m py_compile train.py
        python -m py_compile inference.py
        python -m py_compile data_utils.py
    
    - name: Verify configuration files
      run: |
        python -c "import yaml; yaml.safe_load(open('config.yaml'))"
        python -c "import json; json.load(open('example_data.json'))"
    
    - name: Test data_utils
      run: |
        python data_utils.py --help
